name = "Prominence II Hasturian Era + Distant Horizons (client)"
author = "LunaPixel Studios + dskdkj3"
version = "3.9.26+dh3.0.2-b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40034b8ec07f8dbe7560c6f42a2da83506db42bb7164a8b8d8947a6d4b6b07bc"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
