name = "My Modpack"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e72aa763f4e638f9a07ff3008421740290662e89a921f1db32fecca6666ebe3"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
