name = "My Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37b0989113f062e10f7f7fd8f4adda5ab1e68e8370c9c07d9b459e99ac5e30f0"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
