#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Apr 01 11:24:42 UYT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=Hysteria-Shaders-Universal-v1.2.1.zip
enableShaders=false
